### ISSUE TITLE
Error when processing the output file from the command

### ISSUE THREAD

**Issue by prasadasokan** [3cky/kube-template#11]
We are generating an XML using kube-template and this XML is created as a ConfigMap. The tool throws file already closed exception and when running in the background, it exits with panic: send on closed channel error. 

Can you let me know what's wrong with the approach I'm taking? Any workaround?

The in template reads endpoints of a particular service, and uses that to generate an XML. Then the command invokes an sh file which basically deletes existing ConfigMap and creates another using the output file and then issues a sighup on a running pod. 

Thanks in advance.

**Comment by 3cky** [comment]
Could you provide the stack trace printed when the kube-template panics?

**Comment by prasadasokan** [comment]
@3cky I see that this is happening when I add sleep in the shell script invoked part of command. The need for sleep is due to the delay in the ConfigMap changes propagating to the pod. So a sleep of 3-5s and then invoking sighup seem to cause this issue. Have overcome this by writing the file to a NFS share which is mounted on to the pod and it seem to work for now. But prefer the ConfigMap route and please let me know if there is a way to add 3-5s pause in the shell script without causing a panic at cube-template level.

**Comment by prasadasokan** [comment]
@3cky Also, we are noticing a new pattern when using a NFS share for writing the output file. The command is triggered even when there is no change in the endpoints, and when checking the md5 checksum of the output, it has changed. I think that is causing the command. Is that expected, or it is something that got added due to a NFS share?

**Comment by 3cky** [comment]
@prasadasokan I've added configurable command execution timeout (default 15s). Please test it with your shell script.

**Comment by prasadasokan** [comment]
@3cky Thanks for adding a configurable parameter. Now I no longer see the issue, but the command keeps getting invoked even when there is no change in the endpoint. As mentioned earlier, the md5 of the output file kept changing even when there was no change in the content. Any clue why this is happening? This is triggering an unexpected sighup on the target process.

**Comment by 3cky** [comment]
> As mentioned earlier, the md5 of the output file kept changing even when there was no change in the content.

That's weird. Could you run diff against the files with mentioned md5 changes?
