### ISSUE TITLE
Modern Go dependency management tool

### ISSUE THREAD

**Issue by bpineau** [3cky/kube-template#6]
Hi,
Thanks for this well done and very useful tool!
Refreshing and using the venerable `govendor` tool with more recent versions of the libs (kube's client-go, etc) was a bit challenging.

Would you like us to send a PR updating to `dep` (or even go 1.11 vgo native dependency management)?

**Comment by 3cky** [comment]
Hi @bpineau,

I admit that `govendor` tool is a bit old and barely supported,  but, on the other hand, go 1.11 is still not widely adopted by Linux distros (at least my Fedora 28 still sticks to 1.10). While `dep` tool is definitely better, we'll face the need for transition to "official" vgo dependency management tool in the near future, so maybe we should just await a little more for go 1.11+ widespreading and then switch directly to vgo. 

Anyway, please feel free to send PRs, and thank you for your already submitted PRs, I'll look into them.

**Comment by bpineau** [comment]
Thanks for the comment @3cky

Is the underlying issue project stability over time, or time spent doing throw away work?

If you want to avoid churn due to ephemeral changes, then we won't PR a move from `govendor`.

If you meant to save us time doing ephemeral work, ie. our hypothetical `dep` PR being replaced in a few months, then don't worry, that's ok with me: I'd happily write the conversion in full awareness it won't last (but would help in the meantime). I also don't mind doing it twice, and port to vgo when we're ready to move if you want me to.

**Comment by 3cky** [comment]
Hi @bpineau,

After quite painful session of dependency issues resolving with `govendor` while PR merging, I decided to move to `dep` right now. :) So thank you for the tip.
