### ISSUE TITLE
Error and unable to read pods

### ISSUE THREAD

**Issue by jayakarra** [3cky/kube-template#9]
Build the the top of the tree to find the below error: 

E1210 19:02:46.262412       8 reflector.go:205] kube-template/client_gen.go:50: Failed to list *v1.Pod: pods is forbidden: User "system:serviceaccount:xxxx:lurker-service-account" cannot list resource "pods" in API group "" at the cluster scope.

Below is output of kubectl version:
Client Version: version.Info{Major:“1”, Minor:“14", GitVersion:“v1.14.7”, GitCommit:“8fca2ec50a6133511b771a11559e24191b1aa2b4", GitTreeState:“clean”, BuildDate:“2019-09-18T14:47:22Z”, GoVersion:“go1.12.9”, Compiler:“gc”, Platform:“linux/amd64”}
Server Version: version.Info{Major:“1", Minor:“14+“, GitVersion:“v1.14.8-eks-b7174d”, GitCommit:“b7174db5ee0e30c94a0b9899c20ac980c0850fc8", GitTreeState:“clean”, BuildDate:“2019-10-18T17:56:01Z”, GoVersion:“go1.12.10”, Compiler:“gc”, Platform:“linux/amd64”}

**Comment by 3cky** [comment]
It seems like you're running kubernetes with RBAC enabled, so make sure you have configured your role permissions as it described in [official kubernetes guide](https://kubernetes.io/docs/reference/access-authn-authz/rbac/).

**Comment by jayakarra** [comment]
Thanks for the response. When I run the query via rest API using env variables KUBERNETES_SERVICE_HOST , KUBERNETES_SERVICE_PORT and passing the token, cert in /var/run/secrets/kubernetes.io/serviceaccount, it works. However the same does not work via kube-template

**Comment by jayakarra** [comment]
I can reproduce the issue when the I use default namespace in the rest api. from logs looks like kube-template  (client_gen.go:33) is using  namespace: "default" instead of namespace of service account. 
~ $ kube-template --v 4 --master="http://10..x.x.x:443" --template="/home/xx/tmpl:/home/xx/out" --once
I1213 20:30:40.556473     134 cfg.go:178] poll period set to 15s
I1213 20:30:40.556518     134 cfg.go:191] adding template from command line: /home/xx/tmpl
I1213 20:30:40.556993     134 app.go:105] run once templates processing...
I1213 20:30:40.557003     134 app.go:117] processing template: tmpl
I1213 20:30:40.557032     134 client_gen.go:33] fetching pods, namespace: "default", selector: "xxx"
E1213 20:30:40.558851     134 app.go:144] can't render template: tmpl:2:18: executing "tmpl" at <pods (env "KUBE_NAMESPACE")>: error calling pods: the server rejected our request for an unknown reason (get pods)

**Comment by jayakarra** [comment]
Looks like In cluster Config of client-go not respecting namespace set on service account.

**Comment by 3cky** [comment]
Well, as [described in README](https://github.com/3cky/kube-template#pods), namespace defaults to "default" if not specified. Not sure that changing this behaviour will be correct from backward compatibility point of view. Could you check is your template will be correctly processed with namespace explicitly specified?

**Comment by jayakarra** [comment]
I see my problem, if I use --once the pods are fetched but when poll-period or poll-time is used, its broken. 

~ $ **kube-template --guess-kube-api-settings --config=/tmp/kube-template.yaml --alsologtostderr --v 4** 
I1218 19:56:44.400524     934 cfg.go:91] using config file: /tmp/kube-template.yaml
W1218 19:56:44.400558     934 cfg.go:174] 'poll-time' parameter is deprecated, use 'poll-period' instead
I1218 19:56:44.400566     934 cfg.go:178] poll period set to 1s
I1218 19:56:44.400588     934 cfg.go:218] adding template from config file: /tmp/haproxy_cfg.sh.tmpl
I1218 19:56:44.402167     934 app.go:80] starting templates processing...
I1218 19:56:44.402195     934 app.go:117] processing template: haproxy_cfg.sh.tmpl
I1218 19:56:44.402264     934 client_gen.go:33] fetching pods, namespace: "jkompella-temp6-1501", selector: "appFamily=aoobm"
I1218 19:56:44.402570     934 reflector.go:202] Starting reflector *v1.Pod (0s) from kube-template/client_gen.go:50
I1218 19:56:44.402592     934 reflector.go:240] Listing and watching *v1.Pod from kube-template/client_gen.go:50
E1218 19:56:44.410250     934 reflector.go:205] kube-template/client_gen.go:50: Failed to list *v1.Pod: pods is forbidden: User "system:serviceaccount:jkompella-temp6-1501:lurker-service-account" cannot list resource "pods" in API group "" at the cluster scope
I1218 19:56:45.410368     934 reflector.go:240] Listing and watching *v1.Pod from kube-template/client_gen.go:50
E1218 19:56:45.411909     934 reflector.go:205] kube-template/client_gen.go:50: Failed to list *v1.Pod: pods is forbidden: User "system:serviceaccount:jkompella-temp6-1501:lurker-service-account" cannot list resource "pods" in API group "" at the cluster scope
I1218 19:56:46.412032     934 reflector.go:240] Listing and watching *v1.Pod from kube-template/client_gen.go:50
E1218 19:56:46.413619     934 reflector.go:205] kube-template/client_gen.go:50: Failed to list *v1.Pod: pods is forbidden: User "system:serviceaccount:jkompella-temp6-1501:lurker-service-account" cannot list resource "pods" in API group "" at the cluster scope
I1218 19:56:47.413758     934 reflector.go:240] Listing and watching *v1.Pod from kube-template/client_gen.go:50
E1218 19:56:47.415320     934 reflector.go:205] kube-template/client_gen.go:50: Failed to list *v1.Pod: pods is forbidden: User "system:serviceaccount:jkompella-temp6-1501:lurker-service-account" cannot list resource "pods" in API group "" at the cluster scope
^CI1218 19:56:47.633900     934 cmd.go:161] received interrupt signal...
I1218 19:56:47.633940     934 app.go:163] stopping templates processing...
I1218 19:56:47.633985     934 shared_informer.go:119] stop requested
E1218 19:56:47.634485     934 app.go:144] can't render template: haproxy_cfg.sh.tmpl:2:18: executing "haproxy_cfg.sh.tmpl" at <pods "appFamily=aoobm" "jkompella-temp6-1501">: error calling pods: pod cache sync failed
I1218 19:56:47.634515     934 app.go:97] templates processing stopped
~ $ **kube-template --guess-kube-api-settings --config=/tmp/kube-template.yaml --alsologtostderr --v 4 --once**
I1218 19:56:56.017339     948 cfg.go:91] using config file: /tmp/kube-template.yaml
W1218 19:56:56.017367     948 cfg.go:174] 'poll-time' parameter is deprecated, use 'poll-period' instead
I1218 19:56:56.017375     948 cfg.go:178] poll period set to 1s
I1218 19:56:56.017389     948 cfg.go:218] adding template from config file: /tmp/haproxy_cfg.sh.tmpl
I1218 19:56:56.018729     948 app.go:105] run once templates processing...
I1218 19:56:56.018746     948 app.go:117] processing template: haproxy_cfg.sh.tmpl
I1218 19:56:56.018783     948 client_gen.go:33] fetching pods, namespace: "jkompella-temp6-1501", selector: "appFamily=aoobm"
I1218 19:56:56.036577     948 client_gen.go:33] fetching pods, namespace: "jkompella-temp6-1501", selector: "app=aoobm-sshd"
I1218 19:56:56.044640     948 client_gen.go:33] fetching pods, namespace: "jkompella-temp6-1501", selector: "app=aoobm-http"
I1218 19:56:56.052276     948 client_gen.go:33] fetching pods, namespace: "jkompella-temp6-1501", selector: "app=aoobm-https"
I1218 19:56:56.059626     948 client_gen.go:33] fetching pods, namespace: "jkompella-temp6-1501", selector: "app=aoobm-rdp"
I1218 19:56:56.067792     948 app.go:141] template output not changed: haproxy_cfg.sh.tmpl
I1218 19:56:56.067804     948 app.go:107] templates processed
~ $

**Comment by jayakarra** [comment]
This is duplicate of #12 and hence closing this defect
